[package]
name = "beatdash-desktop"
version = "0.0.0"
description = "BEATDASH Windows Desktop Test Build"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
